<template>
  <v-container class="container-box">  
   <h4>Deep nested static Arrays - with and w/o defined Model </h4>
  
      <!-- FORM-BASE-COMPONENT -->
      <v-form-base 
        id="nested-formbase"
        :model= "myModel"
        :schema= "mySchema"
        @update:modelValue="log"
        />
        <!-- 
          :noAutoModel="true"
          :noAutoSchema="true"
          :noShorthand="true"
          @click="log"
          @focus="log"
          @blur="log"
        -->
      <p>model property 'arrayAutogeneratedModel' doesn't exist and becomes autogenerated from schema definition</p>      
   
    <!-- Stuff  -->    
    <infoline :model="myModel" :schema="mySchema"/>
  </v-container>
</template>

<script setup>
  import vFormBase from '@/vFormBase.vue'
  import { ref, reactive, toRefs, computed, onMounted, onUnmounted } from 'vue'
  import Infoline from '@/components/infoline'
  import { log, logMV } from '@/lib.js'

  const myModel = ref({
    array: [
      true,         
      [
        true,
        false,
        true,
        [
          false,
          true
        ]
      ], 
      true
    ],
    // this model will be autogenerated on the fly
    arrayAutogeneratedModel:[]
  })

  const mySchema = ref({   
    array: [
      { el: 'checkbox', label:'Array-1', color:'#11a'  },         
      [
        { el: 'checkbox', label:'Array-2-1', color:'#a22' },         
        { el: 'checkbox', label:'Array-2-2', color:'#a22' },         
        { el: 'checkbox', label:'Array-2-3', color:'#a22',  },         
        [
          { el: 'checkbox', label:'Array-2-4-1', color:'#2a2' },         
          { el: 'checkbox', label:'Array-2-4-2', color:'#2a2' },         
          { el: 'checkbox', label:'Array-2-4-3', color:'#2a2' }         
        ],
      ],
      // pos = 0 will show element at first position 
      { el: 'checkbox', label:'Array-3 (ORDER FIRST)', color:'#11a', pos:0 },         
    ],

    hr:{el:'divider', color:'red', cols:12},

    arrayAutogeneratedModel: [
      { el: 'checkbox', label:'Autogenerated-Array-1', color:'#11a' },         
      [
        { el: 'checkbox', label:'Autogenerated-Array-2-1', color:'#a22' },         
        { el: 'checkbox', label:'Autogenerated-Array-2-2', color:'#a22' },         
        { el: 'checkbox', label:'Autogenerated-Array-2-3', color:'#a22' },
        [
          { el: 'checkbox', label:'Autogenerated-Array-2-4-1', color:'#2a2' },         
          { el: 'checkbox', label:'Autogenerated-Array-2-4-2', color:'#2a2' },         
          { el: 'checkbox', label:'Autogenerated-Array-2-4-3', color:'#2a2' }         
        ],         
      ],
      { el: 'checkbox', label:'Autogenerated-Array-3', color:'#11a' },         
    ]
    
  })

</script>
