<template>
  <h4>Nested static Arrays - prebuild model '_buildModel=true'</h4>

    <!-- FORM-BASE-COMPONENT -->
    <v-form-base 
      :config="{ _useOrder:true, _buildModel:true }"       
      :model= "myModel"
      :schema= "mySchema"
      cols="4"
      @update:customEvent="logCustomEvent"
    />
   
  <!-- DISPLAY EVENTS, MODEL, SCHEMA and CODE  -->    
  <infoline v-model:modelValue="myModel" v-model:schemaValue="mySchema"/>
</template>

<script setup>
  import vFormBase from '@/vFormBase.vue'
  import { ref, reactive, toRefs, computed, onMounted, onUnmounted } from 'vue'
  import Infoline from '@/components/infoline.vue'
  import { log, logCustomEvent } from '@/lib.js'

  const color = '#1a1'
  const myModel = ref({
    array: [
      false,         
      [
        true,
      ], 
      true
    ],
    
    // this model will be autogenerated on the fly
    // arrayAutogenerated:[]
  })

  const mySchema = ref({   
    array: [
      { el: 'checkbox', label:'Array 0', color  },         
      [
        { el: 'checkbox', label:'Array 1-0', color },         
      ],
      { el: 'checkbox', label:'Array 2', color },         
    ],    

    hr:{el:'divider', cols:12},
    
    arrayAutogenerated: [
      { el: 'checkbox', label:'Auto 0', nullValue:true },         
      [
        { el: 'checkbox', label:'Auto 1-0'  },         
      ],
      { el: 'checkbox', label:'Auto 2' },         
    ]    
  })

</script>
