<template>
  <h4>Deep nested static Arrays - with and w/o defined Model </h4>

    <!-- FORM-BASE-COMPONENT -->
    <v-form-base 
      :config="{ _useOrder:true }"       
      :model= "myModel"
      :schema= "mySchema"
      @update:customEvent="logCustomEvent"
    />
   
  <!-- DISPLAY EVENTS, MODEL, SCHEMA and CODE  -->    
  <infoline v-model:modelValue="myModel" v-model:schemaValue="mySchema"/>
</template>

<script setup>
  import vFormBase from '@/vFormBase.vue'
  import { ref, reactive, toRefs, computed, onMounted, onUnmounted } from 'vue'
  import Infoline from '@/components/infoline.vue'
  import { log, logCustomEvent } from '@/lib.js'

  const myModel = ref({
    array: [
      true,         
      [
        true,
        true,
        [
          false,
          true
        ]
      ], 
      true
    ],
    // this model will be autogenerated on the fly
    arrayAutogenerated:[]
  })

  const mySchema = ref({   
    array: [
      { el: 'checkbox', label:'Array-0', color:'#22e'  },         
      [
        { el: 'checkbox', label:'Array-1-0', color:'#a22' },         
        { el: 'checkbox', label:'Array-1-1', color:'#a22' },         
        [
          { el: 'checkbox', label:'Array-1-2-0', color:'#2a2' },         
          { el: 'checkbox', label:'Array-1-2-1', color:'#2a2' },         
        ],
      ],
      { el: 'checkbox', label:'Array-2 (ORDER FIRST)', color:'#22e', _order:0 },         
    ],

    hr:{el:'divider', color:'red', cols:12},

    arrayAutogenerated: [
      { el: 'checkbox', label:'Autogenerated-0', color:'#11a', nullValue:false },         
      [
        { el: 'checkbox', label:'Autogenerated-Array-1-0', color:'#a22' },         
        { el: 'checkbox', label:'Autogenerated-Array-1-1', color:'#a22' },         
        [
          { el: 'checkbox', label:'Autogenerated-Array-1-2-0', color:'#2a2' },         
          { el: 'checkbox', label:'Autogenerated-Array-1-2-1', color:'#2a2' },         
        ],         
      ],
      { el: 'checkbox', label:'Autogenerated-2', color:'#11a' },         
    ]    
  })

</script>
